# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voice.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_project1(object):
    def setupUi(self, project1):
        project1.setObjectName("project1")
        project1.resize(749, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/technical-support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        project1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(project1)
        self.centralwidget.setObjectName("centralwidget")
        self.client1btn = QtWidgets.QPushButton(self.centralwidget)
        self.client1btn.setGeometry(QtCore.QRect(190, 170, 81, 81))
        self.client1btn.setObjectName("client1btn")
        self.client2btn = QtWidgets.QPushButton(self.centralwidget)
        self.client2btn.setGeometry(QtCore.QRect(280, 170, 81, 81))
        self.client2btn.setObjectName("client2btn")
        self.client3btn = QtWidgets.QPushButton(self.centralwidget)
        self.client3btn.setGeometry(QtCore.QRect(370, 170, 81, 81))
        self.client3btn.setObjectName("client3btn")
        self.client4btn = QtWidgets.QPushButton(self.centralwidget)
        self.client4btn.setGeometry(QtCore.QRect(460, 170, 81, 81))
        self.client4btn.setObjectName("client4btn")
        self.talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.talkbtn.setGeometry(QtCore.QRect(310, 290, 121, 61))
        self.talkbtn.setObjectName("talkbtn")
        project1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(project1)
        self.statusbar.setObjectName("statusbar")
        project1.setStatusBar(self.statusbar)

        self.retranslateUi(project1)
        QtCore.QMetaObject.connectSlotsByName(project1)

    def retranslateUi(self, project1):
        _translate = QtCore.QCoreApplication.translate
        project1.setWindowTitle(_translate("project1", "VOICE"))
        self.client1btn.setText(_translate("project1", "CLIENT 1"))
        self.client2btn.setText(_translate("project1", "CLIENT 2"))
        self.client3btn.setText(_translate("project1", "CLIENT 3"))
        self.client4btn.setText(_translate("project1", "CLIENT 4"))
        self.talkbtn.setText(_translate("project1", "TALK"))
