# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_project1(object):
    def setupUi(self, project1):
        project1.setObjectName("project1")
        project1.resize(749, 571)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/technical-support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        project1.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(project1)
        self.centralwidget.setObjectName("centralwidget")
        self.cl1talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl1talkbtn.setGeometry(QtCore.QRect(190, 170, 81, 81))
        self.cl1talkbtn.setObjectName("cl1talkbtn")
        self.cl2talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl2talkbtn.setGeometry(QtCore.QRect(280, 170, 81, 81))
        self.cl2talkbtn.setObjectName("cl2talkbtn")
        self.cl3talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl3talkbtn.setGeometry(QtCore.QRect(370, 170, 81, 81))
        self.cl3talkbtn.setObjectName("cl3talkbtn")
        self.client4talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.client4talkbtn.setGeometry(QtCore.QRect(460, 170, 81, 81))
        self.client4talkbtn.setObjectName("client4talkbtn")
        self.talkbtn = QtWidgets.QPushButton(self.centralwidget)
        self.talkbtn.setGeometry(QtCore.QRect(310, 290, 121, 61))
        self.talkbtn.setObjectName("talkbtn")
        self.cl3hearbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl3hearbtn.setGeometry(QtCore.QRect(370, 70, 81, 81))
        self.cl3hearbtn.setObjectName("cl3hearbtn")
        self.cl2hearbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl2hearbtn.setGeometry(QtCore.QRect(280, 70, 81, 81))
        self.cl2hearbtn.setObjectName("cl2hearbtn")
        self.cl4hearbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl4hearbtn.setGeometry(QtCore.QRect(460, 70, 81, 81))
        self.cl4hearbtn.setObjectName("cl4hearbtn")
        self.cl1hearbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cl1hearbtn.setGeometry(QtCore.QRect(190, 70, 81, 81))
        self.cl1hearbtn.setObjectName("cl1hearbtn")
        self.HEAR = QtWidgets.QLabel(self.centralwidget)
        self.HEAR.setGeometry(QtCore.QRect(110, 100, 55, 16))
        self.HEAR.setObjectName("HEAR")
        self.BROADCAST = QtWidgets.QLabel(self.centralwidget)
        self.BROADCAST.setGeometry(QtCore.QRect(200, 310, 71, 16))
        self.BROADCAST.setObjectName("BROADCAST")
        self.TALK = QtWidgets.QLabel(self.centralwidget)
        self.TALK.setGeometry(QtCore.QRect(110, 200, 55, 16))
        self.TALK.setObjectName("TALK")
        project1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(project1)
        self.statusbar.setObjectName("statusbar")
        project1.setStatusBar(self.statusbar)

        self.retranslateUi(project1)
        QtCore.QMetaObject.connectSlotsByName(project1)

    def retranslateUi(self, project1):
        _translate = QtCore.QCoreApplication.translate
        project1.setWindowTitle(_translate("project1", "VOICE"))
        self.cl1talkbtn.setText(_translate("project1", "CLIENT 1"))
        self.cl2talkbtn.setText(_translate("project1", "CLIENT 2"))
        self.cl3talkbtn.setText(_translate("project1", "CLIENT 3"))
        self.client4talkbtn.setText(_translate("project1", "CLIENT 4"))
        self.talkbtn.setText(_translate("project1", "TALK"))
        self.cl3hearbtn.setText(_translate("project1", "CLIENT 3"))
        self.cl2hearbtn.setText(_translate("project1", "CLIENT 2"))
        self.cl4hearbtn.setText(_translate("project1", "CLIENT 4"))
        self.cl1hearbtn.setText(_translate("project1", "CLIENT 1"))
        self.HEAR.setText(_translate("project1", "HEAR"))
        self.BROADCAST.setText(_translate("project1", "BROADCAST"))
        self.TALK.setText(_translate("project1", "TALK"))
